### ISSUE TITLE
trouble connecting to daemon

### ISSUE THREAD

**Issue by okwme** [dereuromark/CakePHP-Payment-Plugin#1]
hi i'm trying this on a local set up with MAMP on my mac. I've got a daemon running but i'm not able to connect with the plugin. I don't see where the location of the damon is set in the code though. mine is inside of my ~/Documents folder and i probably need to state that explicitly somewhere, right?

**Comment by dereuromark** [comment]
See the configure values around https://github.com/dereuromark/CakePHP-Payment-Plugin/blob/master/Lib/BitcoinLib.php#L46 and the defaults available.

**Comment by okwme** [comment]
Hi, Thank you for your reply! My configs are getting combined correctly on line 46 with the defaults. I can test it by debugging the bitcoin client and see that my username account name and password are all set but i still get an error message of Connect error: Connection refused (61) when i try to use the client

**Comment by okwme** [comment]
got it now! i was connecting to the wrong port : )
