### ISSUE TITLE
Tools Plugin

### ISSUE THREAD

**Issue by okwme** [dereuromark/CakePHP-Payment-Plugin#2]
Hi, I keep getting errors on the classes that are provided by your tools plugin. I have included the Plugin in my app/Plugin folder as well as my bootstrap but still get errors like:
Call to a member function isPosted() on a non-object in app/Plugin/Payment/Controller/BitcoinAddressesController.php on line 36

How do i properly include the Tools Plugin to fix this?

**Comment by dereuromark** [comment]
See the method and what class it belongs to
You would need to include the Tools.Common component here in your AppController or make a PR to include that component in the PaymentAppController.

**Comment by okwme** [comment]
Aha! Thank you : )
