### ISSUE TITLE
Call to a member function find() on a non-object BitcoinAddressesController.php

### ISSUE THREAD

**Issue by zot24** [dereuromark/CakePHP-Payment-Plugin#3]
There is not `User` related with `BitcoinAddress` Model and that call is throwing an exceptiong, what could be happening?

```
$users = $this->BitcoinAddress->User->find('list');
```

**Comment by dereuromark** [comment]
I havent used it for years. Please provide patches with PRs in the future :)
I fixed this one with https://github.com/dereuromark/CakePHP-Payment-Plugin/commit/f3ba819abea5d6f4c3ed8e88035619c4a3a8e592

**Comment by zot24** [comment]
Thanks! I'll
